classical_models = [
    'tabm',
    'xgboost',
    'logreg',
    'ncm',
    'lightgbm',
    'naivebayes',
    'knn',
    'randomforest',
    'catboost',
    'svm',
    'dummy',
    'linearregression'
]

deep_models = ["mlp",'resnet', 'node', 'ftt', 'tabptm','tabpfn',   'tabr', 'modernNCA',  'tabcaps', 'tabnet', 'saint', 'tangos',  'tangos',
    'snn',
    'ptarl',
    'danets',
    'dcn2',
    'tabtransformer',
    'grownet',
    'autoint',
    'dnnr',
    'switchtab',
    'hyperfast',
    'bishop',
    'protogate',
    'realmlp',
    'mlp_plr',
    'excelformer',
    'grande',
    'amformer',
    'trompt',
    'tabm']